2025-08-24 18:55:15,900 ERROR: Exception on /solutions/dcis [GET] [in C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "D:\BeRAM-Website\beram\solutions\routes.py", line 32, in solution_detail
    return render_template('dcis_detail.html',
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 1016, in get_template
    return self._load_template(name, globals)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 771, in compile
    self.handle_exception(source=source_hint)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\BeRAM-Website\beram\templates\dcis_detail.html", line 214, in template
    <a href="{{ url_for('main.request_demo') }}" class="btn btn-outline-primary btn-lg">Request a Demo</a>
jinja2.exceptions.TemplateSyntaxError: Unexpected end of template. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2025-08-24 18:55:15,920 ERROR: Server Error: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application. [in D:\BeRAM-Website\beram\errors.py:15]
2025-08-24 18:55:36,051 INFO: BeRAM startup [in D:\BeRAM-Website\beram\errors.py:44]
2025-08-24 18:55:36,559 INFO: BeRAM startup [in D:\BeRAM-Website\beram\errors.py:44]
2025-08-24 18:55:49,063 INFO: BeRAM startup [in D:\BeRAM-Website\beram\errors.py:44]
2025-08-24 18:55:59,930 ERROR: Exception on /solutions/dcis [GET] [in C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "D:\BeRAM-Website\beram\solutions\routes.py", line 32, in solution_detail
    return render_template('dcis_detail.html',
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 1016, in get_template
    return self._load_template(name, globals)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 771, in compile
    self.handle_exception(source=source_hint)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\BeRAM-Website\beram\templates\dcis_detail.html", line 214, in template
    <a href="{{ url_for('main.request_demo') }}" class="btn btn-outline-primary btn-lg">Request a Demo</a>
jinja2.exceptions.TemplateSyntaxError: Unexpected end of template. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2025-08-24 18:55:59,933 ERROR: Server Error: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application. [in D:\BeRAM-Website\beram\errors.py:15]
2025-08-24 18:56:01,596 ERROR: Exception on /solutions/dcis [GET] [in C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "D:\BeRAM-Website\beram\solutions\routes.py", line 32, in solution_detail
    return render_template('dcis_detail.html',
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 1016, in get_template
    return self._load_template(name, globals)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 771, in compile
    self.handle_exception(source=source_hint)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\BeRAM-Website\beram\templates\dcis_detail.html", line 214, in template
    <a href="{{ url_for('main.request_demo') }}" class="btn btn-outline-primary btn-lg">Request a Demo</a>
jinja2.exceptions.TemplateSyntaxError: Unexpected end of template. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2025-08-24 18:56:01,599 ERROR: Server Error: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application. [in D:\BeRAM-Website\beram\errors.py:15]
2025-08-24 18:56:10,440 INFO: BeRAM startup [in D:\BeRAM-Website\beram\errors.py:44]
2025-08-24 18:56:10,849 INFO: BeRAM startup [in D:\BeRAM-Website\beram\errors.py:44]
2025-08-24 19:21:06,237 INFO: BeRAM startup [in D:\BeRAM-Website\beram\errors.py:44]
2025-08-24 19:21:06,682 INFO: BeRAM startup [in D:\BeRAM-Website\beram\errors.py:44]
2025-08-24 19:21:12,015 INFO: BeRAM startup [in D:\BeRAM-Website\beram\errors.py:44]
2025-08-24 19:24:27,772 INFO: BeRAM startup [in D:\BeRAM-Website\beram\errors.py:44]
2025-08-24 19:25:34,559 ERROR: Server Error: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application. [in D:\BeRAM-Website\beram\errors.py:15]
